### ISSUE TITLE
관리자 기능 FAQ 

### ISSUE THREAD

**Issue by Leeeunsookl** [k-mcp/My_Class_Planner#23]
**기능에 문제가 있나요?**
관리자만 사용할 수 있는 FAQ 

**해결책**
administration 계정 넣고,  FAQ 커뮤니티 게시판 공지사항으로 게시판 넣기 

**다른 해결책**
side bar에 추가하는 것 고민

**Comment by tesla1220** [comment]
<FAQ 목록> : 관리자에게만 보여지는 페이지로 추후 커뮤니티 상단에 배치할 예정

**FAQ**

이미 저장된 시간표를 바로 확인하고 싶어요.
좌측 상단의 로고를 클릭해주세요

코스는 뭐고 섹션은 뭔가요?
코스 - 과목명 / 섹션 - 과목에 해당하는 수업 시간들
=> 한 가지 코스에 여러 개 섹션을 넣을 수 있다.

코스에 한 가지 과목밖에 등록 가능?
맞습니다. 과목은 한 개만 존재하기 때문에 같은 과목의 다른 강의일 경우 섹션에 추가해주세요.
다른 과목을 추가하고 싶다면 기존 섹션 및 코스를 서밋한 후에 새 코스를 추가해주세요


코스와 섹션은 한 번에 몇 개까지 등록 가능?
무제한


MyCourses 는 뭔가요?
Add Course 에서 저장된 과목들과 섹션들을 확인할 수 있는 공간. 확인 후 내용이 맞으면 generate 버튼을 눌러주세요

이미 저장된 섹션에 섹션을 더 추가하고 싶어요
addCourse에서 과목명을 동일하게 입력 후, 섹션을 추가해주시면 자동으로 MyCourse에 수정된 섹션을 확인할 수 있습니다. 


더 자세한 사용법을 알고 싶어요.
사이드 바의 홈 혹은  화면 상단의 Hello user  클릭 후 how to use 를 참고해주세요.
서비스 이용은 사이드바의 카테고리 순서대로 진행됩니다. 각 카테고리 별 우측 하단에 있는 Next 버튼을 클릭하시면 서비스 이용 순서대로 진행됩니다.

=======================================사용법==========================

게스트와 회원의 차이점은?
게스트로도 이용은 가능하나, 일회성으로만 이용가능하고 생성된 시간표가 저장되지 않습니다. 이 때문에 추후 확인이 어렵기 때문에 회원 가입을 권장


계정을 삭제하고 싶어요
서비스 이용을 잠시 중단할 수 있습니다. 세팅 창에서 계정 상태를 디액티베이트로 변경해주세요. 
영구 탈퇴를 원한다면 컨택 어스를 통해 이메일로 전달해주세요.

FAQ 에서 제가 질문하고 싶은 내용을 찾을 수가 없어요.
일반 회원분들은 커뮤니티에 질문을 올려주시면 관리자에게 댓글로 답변을 받으실 수 있습니다.
게스트의 경우, 커뮤니티에서 검색창에 질문 내용을 입력하시면 관련 내용을 확인하실 수 있습니다. 
해결되지 못한 질문들은 Contact Us 를 통해 연락주시면 이메일로 답변을 받아보실 수 있습니다.

**Comment by tesla1220** [comment]
How do I  check my already saved schedule?
Please click on the logo in the top left corner, or you can also click ‘My Plans’ on the sidebar.

What is a course and what is a section?
Course - the name of the subject / Section - the class times corresponding to the subject
=> Multiple sections can be added to a single course.


Can only one subject be registered per course?
Yes, that is correct. Since there can only be one subject, please add different lectures of the same subject under sections.
If you want to add another subject, please submit the existing sections and course, then add a new course.


How many courses and sections can be registered at once?
There is no limit. But if you add too many subjects at once, the possible time schedule might be limited.

What is MyCourses?
It is a space where you can check the saved subjects and sections from 'Add Course'. If the content is correct, please click the generate button.


Can I add more sections to an already saved section?
Yes, please enter the same subject name in 'Add Course', then add the section. The updated sections can be automatically viewed in 'My Course'.


How do I see more detailed instructions?
Please refer to 'how to use' by clicking 'Home' on the sidebar or click 'Hello user(your username)' at the top of the screen on the sidebar.
Service use proceeds in the order of the categories on the sidebar or click the Next button in the bottom right corner of each category page to proceed in order.


Can I use the service as a guest?
Yes. But guests can use the service but only on a one-time basis, and the created schedules are not saved. Therefore, we recommend registering as a member for future reference.

How do I delete my account?
You can temporarily suspend the use of the service. You can change the account status to deactivate in the 'Settings'.
For permanent deletion, please contact us via email on the 'Contact Us'.

I can't find the answer to my question in the FAQ.
If you are a user, users can post questions in the community and receive responses from us in the comments.
if you are a guest, guests can enter their questions in the search bar in the community to find related information.
If you have more questions, please contact us through 'Contact Us' page on the sidebar and you will receive an email response.
